### ISSUE TITLE
Not exporting partnerDiscount

### ISSUE THREAD

**Issue by elbotho** [goodmap/gooddb-backend#46]
Since #44 `additionalProperties.future.discountAmount` is removed but the new `additionalProperties.future. partnerDiscount` is also not accessible. 

Example:
https://api.gooddb.io/v1/places/free?futureIsPartner=true&region[]=M%C3%BCnchen

**Comment by benediktdertinger** [comment]
Hi @elbotho, thanks for submitting. This is not a bug. The data was simply not added in the CSV and therefore could not be imported. I updated all partners manually and you can now access the requested fields.

**Comment by elbotho** [comment]
Thank you @benediktdertinger! 
Already working. Do the relevant people know that the need to add this?

**Comment by benediktdertinger** [comment]
Hi @elbotho, yes they do. In the backend interface it is not possible to set a place as partner without adding the `partnerDiscount` value.
